NUMBER_OF_LEADING_ZEROS = 3
BLOCK_REWARD = 6
NETWORK_DEFAULT = 'nig'
ROUND_VALUE_DIGIT = 4
DEFAULT_TRANSACTION_FEE_PERCENTAGE = 0.1
INTERFACE_TRANSACTION_FEE_SHARE = 30
NODE_TRANSACTION_FEE_SHARE = 20
MINER_TRANSACTION_FEE_SHARE = 50
INTERFACE_BLOCK_REWARD_PERCENTAGE = 30
NODE_BLOCK_REWARD_PERCENTAGE = 20
MINER_BLOCK_REWARD_PERCENTAGE = 50
EUR_NIG_VALUE_START_TIMESTAMP = 1713657600
EUR_NIG_VALUE_START_CONVERSION_RATE = 1
EUR_NIG_VALUE_START_INCREASE_DAILY_PERCENTAGE = 1
EUR_NIG_VALUE_START_INCREASE_HALVING_DAYS = 360
LEADER_NODE_SCHEDULE_NB_SLOT=4
MARKETPLACE_SELLER_SAFETY_COEF=2
MARKETPLACE_BUYER_SAFETY_COEF=1

CONTEST_PUBLIC_KEY_HASH='9ee93ba03f12c3a9e04b7982b5e4b657654aa74a'
APPLICATION_VERSION_PUBLIC_KEY_HASH='0ee93ba03f12c3a9e04b7982b5e4b657654aa74a'
MARKETPLACE_CODE_PUBLIC_KEY_HASH='41e69d07d38a4d7cca36df456ef099e8efb0512d'
REPUTATION_CODE_PUBLIC_KEY_HASH='7c2043277fc30413cdfa5224d228c449ef2586c9'
MARKETPLACE_STEP1_EXPIRATION=604800
#MARKETPLACE_STEP1_EXPIRATION=12000
MARKETPLACE_STEP2_EXPIRATION=2592000
#MARKETPLACE_STEP2_EXPIRATION=12000
MARKETPLACE_STEP3_EXPIRATION=2592000
#MARKETPLACE_STEP3_EXPIRATION=12000

#threshold to ensure that only user with great reputation can sell to new user to avoid issue
#THRESHOLD0_TO_SALE_2_NEWUSER = nb of transaction with reputation
#THRESHOLD1_TO_SALE_2_NEWUSER = reliability
#THRESHOLD0_TO_SALE_2_NEWUSER=10
#THRESHOLD1_TO_SALE_2_NEWUSER=99
THRESHOLD0_TO_SALE_2_NEWUSER=0
THRESHOLD1_TO_SALE_2_NEWUSER=0

#flag use to check the reputation of a seller to a new buyer
CHECK_SELLER_REPUTATION_FLAG_FOR_NEW_BUYER=False

#SERVER SETUP
#MY_NODE="server_node3"
#MY_HOSTNAME = 'vps90852.serveur-vps.net'
#NODE_FILES_ROOT = r'/home/pierre/nig_node'
#FIRST_KNOWN_NODE_HOSTNAME_LIST = ["vps90843.serveur-vps.net","vps90851.serveur-vps.net","vps90852.serveur-vps.net"]
#NODE_TO_AVOID_HOSTNAME1 = {'hostname': 'vps90843.serveur-vps.net'}
#NODE_TO_AVOID_HOSTNAME3 = {'hostname': 'vps90852.serveur-vps.net'}
#MEMPOOL_DIR = NODE_FILES_ROOT+r'/files/MEMPOOL_DIR.txt'
#KNOWN_NODES_DIR = NODE_FILES_ROOT+r'/files/KNOWN_NODES_DIR.txt'
#LEADER_NODE_SCHEDULE_DIR = NODE_FILES_ROOT+r'/files/LEADER_NODE_SCHEDULE_DIR.txt'
#BLOCKCHAIN_DIR = NODE_FILES_ROOT+r'/files/BLOCKCHAIN_DIR.txt'
#STORAGE_DIR = NODE_FILES_ROOT+r'/STORAGE'
#MASTER_STATE_DIR = r'/master_state'
#MASTER_STATE_DIR_TEMP = r'/master_state_temp'
#LEADER_NODE_TRANSACTIONS_ADVANCE = r'/leader_node_advance'
#MASTER_STATE_DEEPTH=3
#NEW_BLOCKCHAIN_DIR = r'/blockchain'
#NEW_BLOCKCHAIN_DIR_BACKLOG = r'/blockchain_backlog'
#NEW_BLOCKCHAIN_DIR_SLASHED = r'/blockchain_slashed'
#NEW_BLOCKCHAIN_DIR_NB_SLOT_BEFORE_REVOTE=2
#NEW_BLOCKCHAIN_DIR_NB_SLOT_BEFORE_BLOCKCHAIN=4
#NEW_BLOCKCHAIN_DIR_SLASHED_NB_SLOT_BEFORE_ARCHIVE=10
#NEW_BLOCKCHAIN_DEEPTH=3
#NEW_BLOCKCHAIN_SLASHED_DEEPTH=0
#PoH_DURATION_SEC=10


#LOCAL SETUP
MY_NODE="local_node3"
MY_HOSTNAME = '127.0.0.3:5000'
NODE_FILES_ROOT = r'C:\Users\davidlio\source\nig\node3'
FIRST_KNOWN_NODE_HOSTNAME_LIST = ["127.0.0.1:5000","127.0.0.2:5000","127.0.0.3:5000"]
NODE_TO_AVOID_HOSTNAME1 = {'hostname': '127.0.0.1:5000'}
NODE_TO_AVOID_HOSTNAME3 = {'hostname': '127.0.0.3:5000'}
MEMPOOL_DIR = NODE_FILES_ROOT+r'\files\MEMPOOL_DIR.txt'
KNOWN_NODES_DIR = NODE_FILES_ROOT+r'\files\KNOWN_NODES_DIR.txt'
LEADER_NODE_SCHEDULE_DIR = NODE_FILES_ROOT+r'\files\LEADER_NODE_SCHEDULE_DIR.txt'
BLOCKCHAIN_DIR = NODE_FILES_ROOT+r'\files\BLOCKCHAIN_DIR.txt'
STORAGE_DIR = NODE_FILES_ROOT+r'\STORAGE'
MASTER_STATE_DIR = r'\master_state'
MASTER_STATE_DIR_TEMP = r'\master_state_temp'
LEADER_NODE_TRANSACTIONS_ADVANCE = r'\leader_node_advance'
MASTER_STATE_DEEPTH=0
NEW_BLOCKCHAIN_DIR = r'\blockchain'
NEW_BLOCKCHAIN_DIR_BACKLOG = r'\blockchain_backlog'
NEW_BLOCKCHAIN_DIR_SLASHED = r'\blockchain_slashed'
NEW_BLOCKCHAIN_DIR_NB_SLOT_BEFORE_REVOTE=2
NEW_BLOCKCHAIN_DIR_NB_SLOT_BEFORE_BLOCKCHAIN=4
NEW_BLOCKCHAIN_DIR_SLASHED_NB_SLOT_BEFORE_ARCHIVE=10
NEW_BLOCKCHAIN_DEEPTH=0
NEW_BLOCKCHAIN_SLASHED_DEEPTH=0
PoH_DURATION_SEC=10